dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
env:
  global:
    - GH_TOKEN=$GH_TOKEN
before_install:
  - chmod +x .travis/push.sh
# command to install dependencies
install:
  - pip install -r requirements.dev.txt
# command to run tests
script:
  - python watch.py
deploy:
  provider: script
  script: .travis/push.sh
